export enum VideoStatus {
  REQUESTED = 'requested',
  QUEUED = 'queued',
  RESEARCHING = 'researching',
  RESEARCH_FAILED = 'research_failed',
  SCRIPT_GENERATING = 'script_generating',
  SCRIPT_GENERATION_FAILED = 'script_generation_failed',
  PLANNING = 'planning',
  PLANNING_FAILED = 'planning_failed',
  GENERATING_MEDIA = 'generating_media',
  MEDIA_GENERATION_FAILED = 'media_generation_failed',
  MEDIA_READY = 'media_ready',
  RENDERING = 'rendering',
  RENDERING_FAILED = 'rendering_failed',
  QUALITY_CHECK = 'quality_check',
  QUALITY_CHECK_FAILED = 'quality_check_failed',
  READY_TO_PUBLISH = 'ready_to_publish',
  PUBLISHING = 'publishing',
  PUBLISHING_FAILED = 'publishing_failed',
  PUBLISHED = 'published',
}
