## Post Request for SocialAccounts Controller

POST http://localhost:3000/social-accounts/youtube/link
Content-Type: application/json

{
    "channelId": "1234567890",
    "channelName": "Marcelsnews",
    "niche": "news"
}