## Get Request for Users Controller

GET http://localhost:3000/users?page=1&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNjViOGY2ZS1iZDBjLTRlNWQtYTZjOS1jZDQwNzFlNTA5OGEiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYxNTY2MDQxLCJleHAiOjE3NjE1Njk2NDEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.ySzYpSscUBpNmmzsovFSAwiLTitOynNel4KWbxdcSFg

GET http://localhost:3000/users/365b8f6e-bd0c-4e5d-a6c9-cd4071e5098a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNjViOGY2ZS1iZDBjLTRlNWQtYTZjOS1jZDQwNzFlNTA5OGEiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYxNTY2MDQxLCJleHAiOjE3NjE1Njk2NDEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.ySzYpSscUBpNmmzsovFSAwiLTitOynNel4KWbxdcSFg

