## Post Request for Users Controller

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "ahmaddialo@yahoo.com",
    "userName": "Ahmaddialo",
    "password": "ahmaddialo#113"
    // "preferences": {
    //     "frequencyOfUpload": 1,
    //     "autoPost": false,
    //     "replyTone": "WITTY"
    // }
}