## Update Request for Users Preferences Controller

PATCH  http://localhost:3000/users/preferences
Content-Type: application/json

{
    "frequencyOfUpload": 2,
    "autoPost": true,
    "replyTone": "WITTY"
}