## Get Request for Users Controller

GET http://localhost:3000/users?page=1&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNTkxMTdhNi0wNGUyLTQwNTEtYTliOS1jYjUwMjRkMTdlM2EiLCJlbWFpbCI6Im1hcmNlbEBnbWFpbC5jb20iLCJpYXQiOjE3NjAyNjEzMzcsImV4cCI6MTc2MDI2NDkzNywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.s0PhK8xlm3st-Yx1CM0RjmXFnalC-Ydo_yJpUgAUyDM

GET http://localhost:3000/users/b229f0df-4a5f-4999-b996-e30141424235
