## Get Request for Users Controller

GET http://localhost:3000/users?page=1&limit=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMzMzMzRmMy01ZGZjLTQyMDUtOWYxOS0yOTFjZjAyOTY1MDMiLCJlbWFpbCI6Im1hcmNlbEB5YWhvby5jb20iLCJpYXQiOjE3NjEwOTEzNzAsImV4cCI6MTc2MTA5NDk3MCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.C9j4fXa9S5VxfghHCI_qcF9R4sr9dGrAOmYFhtPAU3M

GET http://localhost:3000/users/b229f0df-4a5f-4999-b996-e30141424235
