## Update Request for Users Controller

PATCH  http://localhost:3000/users/98ef9bd1-bc22-4c48-bb40-2bd9da1f4903
Content-Type: application/json

{
    "email": "marcel@gmail.com",
    "userName": "marcelalexis"
}