import * as Joi from 'joi';

export default Joi.object({
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().port().default(6379),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().port().default(5432),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_DATABASE: Joi.string().required(),
  DB_SYNC: Joi.boolean().required(),
  DB_AUTOLOAD: Joi.boolean().required(),
  CLERK_SECRET_KEY: Joi.string().required(),
  CLERK_PUBLISHABLE_KEY: Joi.string().optional(),
  JWT_SECRET: Joi.string().optional(),
  JWT_TOKEN_AUDIENCE: Joi.string().optional(),
  JWT_TOKEN_ISSUER: Joi.string().optional(),
  JWT_ACCESS_TOKEN_TTL: Joi.number().optional(),
  JWT_REFRESH_TOKEN_TTL: Joi.number().optional(),
  GOOGLE_CLIENT_ID: Joi.string().optional(),
  GOOGLE_CLIENT_SECRET: Joi.string().optional(),
  GOOGLE_REDIRECT_URI: Joi.string().optional(),
  FACEBOOK_APP_ID: Joi.number().optional(),
  FACEBOOK_CLIENT_SECRET: Joi.string().optional(),
  API_VERSION: Joi.string().required(),
  ADMIN_EMAIL: Joi.string().required(),
  ADMIN_PASSWORD: Joi.string().required(),
  ENCRYPTION_KEY: Joi.string().required(),
});
