import * as Joi from 'joi'

export default Joi.object({
    REDIS_HOST: Joi.string().default('localhost'),
    REDIS_PORT: Joi.number().port().default(6379),
    LOGO_REQUEST_STREAM: Joi.string().optional(),
    LOGO_RESULT_STREAM: Joi.string().optional(),
    LOGO_DETECTION_TIMEOUT_MS: Joi.number().integer().positive().optional(),
    LOGO_DETECTION_CONF: Joi.number().min(0).max(1).optional(),
    LOGO_DETECTION_IOU: Joi.number().min(0).max(1).optional(),
    LOGO_DETECTION_MIN_SEGMENT_FRAMES: Joi.number().integer().min(1).optional(),
    LOGO_DETECTION_MAX_FRAME_GAP: Joi.number().integer().min(0).optional(),
    LOGO_DETECTION_CONTINUITY_IOU: Joi.number().min(0).max(1).optional(),
    LOGO_DETECTION_WEIGHTS: Joi.string().optional(),
    LOGO_DETECTION_MAX_FRAMES: Joi.number().integer().min(1).optional(),
    DB_HOST: Joi.string().required(),
    DB_PORT: Joi.number().port().default(5432),
    DB_USERNAME: Joi.string().required(),
    DB_PASSWORD: Joi.string().required(),
    DB_DATABASE: Joi.string().required(),
    DB_SYNC: Joi.boolean().required(),
    DB_AUTOLOAD: Joi.boolean().required(),
    JWT_SECRET: Joi.string().required(),
    JWT_TOKEN_AUDIENCE: Joi.string().required(),
    JWT_TOKEN_ISSUER: Joi.string().required(),
    JWT_ACCESS_TOKEN_TTL: Joi.number().required(),
    JWT_REFRESH_TOKEN_TTL: Joi.number().required(),
    GOOGLE_CLIENT_ID: Joi.string().required(),
    GOOGLE_CLIENT_SECRET: Joi.string().required(),
    GOOGLE_REDIRECT_URI: Joi.string().required(),
    FACEBOOK_APP_ID: Joi.number().required(),
    FACEBOOK_CLIENT_SECRET: Joi.string().required(),
    API_VERSION: Joi.string().required(),
    ADMIN_EMAIL: Joi.string().required(),
    ADMIN_PASSWORD: Joi.string().required(),
    ENCRYPTION_KEY: Joi.string().required()
})