## Post Request for Auth Controller

POST http://localhost:3000/auth/sign-in
Content-Type: application/json

// {
//     "email": "johndoe@gmail.com",
//     "password": "JohnDoe123#"
  
// }

{
    "email": "marcel@yahoo.com",
    "password": "marcelalexis#113"
  
}

